title: Karthikeshwar
author:
  name: Karthikeshwar
  email: karthikeshwar7087@gmail.com
description: Personal Website
show_excerpts: false # set to false to remove excerpts on the homepage

header_pages:
  - blog.md
  - projects.md
  - musings.md

# Build settings
theme: minima

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
#   skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: karthikeshwar1

github_username: karthikeshwar1

# plugins:
#   - jekyll-feed
