title: Karthikeshwar
author:
  name: Karthikeshwar
  email: karthikeshwar7087@gmail.com
description: Karthikeshwar's official website
show_excerpts: false # set to false to remove excerpts on the homepage

header_pages:
  - blog.md

# Build settings
theme: minima

github_username: karthikeshwar1

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: karthikeshwar1

